### ISSUE TITLE
Add support for deploying with IaC

### ISSUE THREAD

**Issue by noamsdahan** [ermetic/access-undenied-aws#8]
Add the ability to deploy the roles and permissions that access undenied needs with infrastructure as code (CloudFormation/Terraform/Pulumi/AWS CDK)

- Deploy role in management account with custom policies
- Deploy roles in managed account trusting managed account

Optional follow-up issue: deploy lambda.

**Comment by JonHolman** [comment]
I'm working on deploying it via AWS CDK.  I wanted to make get_scps from within the function, so it doesn't have to be manually updated, but I haven't figured out how to do that yet.

**Comment by noamsdahan** [comment]
That's great!
I'll take a look at this on Sunday or Monday.
What I think we should do is not run through the get_scps function but directly through the initialize_organization_data function.
With that there are two options:

- Create a common.Config object to use as input (like I did in the Lambda example at /examples/lambda/lambda_handler.py)
- Pare down the signature of initialize_organization_data so that it doesn't require a common.Config object.

**Comment by JonHolman** [comment]
What I have so far is available at https://github.com/JonHolman/access-undenied-aws/tree/main/examples/lambda-cdk
I just put scp_data.json in the same directory as that Lambda function (fns), but I did not commit it.  So to test as is, you would need to put your scp_data.json file in that location and you would also need to update the management account ID at https://github.com/JonHolman/access-undenied-aws/blob/main/examples/lambda-cdk/lambda_cdk/lambda_cdk_stack.py#L53

**Comment by noamsdahan** [comment]
Thank you!
Initial version merged.
Support for SCP retrieval and storage in an S3 bucket --> for future implementation.
